pagination:
  per: 25
  max_per: 100
scopes:
  read:
    - resources
    - resources:read
    - types
    - types:read
  write:
    - resources
    - types
property:
  types:
    - text
    - number
    - range
    - color
    - password
    - date
    - time
    - datetime
    - url
categories:
  - lights
  - locks
  - thermostats
  - alarms
  - meters
  - cameras
  - windows
  - appliances
  - garddenings
  - sensors
  - others
