device:
  host: <%= device_host = "https://device.lelylan.com" %>
  uri: <%= "#{device_host}/devices/closet-dimmer" %>
  another:
    uri: <%= "#{device_host}/devices/another-closet-dimmer" %>

type:
  host: <%= type_host = "https://type.lelylan.com" %>
  uri: <%= "#{type_host}/types/dimmer" %>
  another:
    uri: <%= "#{type_host}/types/another-dimmer" %>

user: 
  host: <%= people_host = "https://people.lelylan.com" %>
  auth: <%= "#{people_host}/authentication" %>
  uri: <%= "#{people_host}/users/alice" %>
  email: 'alice@example.com'
  password: 'example'
  another: 
    uri: <%= "#{people_host}/users/bob" %>
    email: 'bob@example.com'

properties:
  status:
    uri: <%= status_uri = "#{type_host}/properties/status" %> 
    property_id: 'status'
    name: 'Status'
    default: 'off'
    values: ['on', 'off']
    new: 'on'
  intensity:
    uri: <%= intensity_uri = "#{type_host}/properties/intensity" %> 
    property_id: 'intensity'
    name: 'Intensity'
    default: '0.0'
    values: ['0', '10', '20', '30', '40', '50', '60', '70', '80', '90', '100']
    new: '100.0'
  another:
    uri: <%= "#{type_host}/properties/another-property" %>
    property_id: 'another-property'
    value: '75.0'

functions:
  set_intensity:
    name: 'Set intensity'
    function_id: 'set-intensity'
    uri: <%= set_intensity_uri = "#{type_host}/functions/set-intensity" %>
  turn_on:
    name: 'Turn on'
    function_id: 'turn-on'
    uri: <%= turn_on_uri = "#{type_host}/functions/turn-on" %>
  turn_off:
    name: 'Turn off'
    function_id: 'turn-off'
    uri: <%= turn_off_uri = "#{type_host}/functions/turn-off" %>
  another:
    name: 'Another function'
    uri: <%= "#{type_host}/functions/another-function" %>

statuses:
  setting_intensity:
    status_id: 'setting-intensity'
    uri: <%= "#{type_host}/statuses/setting-intensity" %>
    name: 'Setting intensity'

validation:
  uris:
    valid: ['http://example.com', 'http://www.examle.com']
    not_valid: ['example', 'example.com', 'www.example.com']
